version: '2'

services: 
  db: 
    image: postgres:12.12
    environment: 
      POSTGRES_USER: aishwarya
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sunrise_temp
    volumes:
      - db-data:/usr/local/pgsql/data
    ports: 
      - '5433:5432'
  app: 
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on: 
      - db

volumes:
  db-data:
    external: false
